#ifndef SYSLOG_SEVERITY_H_
#define SYSLOG_SEVERITY_H_ 1

#define SYSLOG_SEVERITY_EMERGENCY (0)
#define SYSLOG_SEVERITY_ALERT (1)
#define SYSLOG_SEVERITY_CRITICAL (2)
#define SYSLOG_SEVERITY_ERROR (3)
#define SYSLOG_SEVERITY_WARNING (4)
#define SYSLOG_SEVERITY_NOTICE (5)
#define SYSLOG_SEVERITY_INFO (6)
#define SYSLOG_SEVERITY_DEBUG (7)

#endif // SYSLOG_SEVERITY_H_
